server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/sakila
    username: postgres
    password: 1234
  jooq:
    sql-dialect: postgres

logging:
  level:
    org:
      jooq:
        tools:
          LoggerListener: debug