services:
  postgres:
    container_name: postgres
    image: postgres:17-alpine3.21
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - db-network
    environment:
      POSTGRES_PASSWORD: 1234

volumes:
  postgres-data: { }

networks:
  db-network: { }
